const { GoogleGenerativeAI } = require("@google/generative-ai"); 
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer")

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GENAI_API_KEY);

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    
    const model = genAI.getGenerativeModel({ 
        model: "gemini-2.5-flash", 
        generationConfig: {
            responseMimeType: "application/json",
            responseSchema: interviewReportSchema 
        }
    });

    const prompt = `
        Analyze the following candidate details against the Job Description.
        Return a detailed interview report in JSON format.
        
        Resume: ${resume}
        Self Description: ${selfDescription}
        Job Description: ${jobDescription}
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    
    const text = response.text(); 
    
    return JSON.parse(text);
}


const interviewReportSchema = {
    type: "object",
    properties: {
        
        matchScore: { 
            type: "integer", 
            description: "An integer percentage from 0 to 100. Do not use decimals."
        },
        technicalQuestions: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    question: { type: "string" },
                    intention: { type: "string" },
                    answer: { type: "string" }
                }
            }
        },
        behavioralQuestions: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    question: { type: "string" },
                    intention: { type: "string" },
                    answer: { type: "string" }
                }
            }
        },
        skillGaps: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    skill: { type: "string" },
                    severity: { type: "string", enum: ["low", "medium", "high"] }
                }
            }
        },
        preparationPlan: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    day: { type: "number" },
                    focus: { type: "string" },
                    tasks: { type: "array", items: { type: "string" } }
                }
            }
        },
        title:{
            type:"string",
            description: "The title of the job for which the interview report is generated"
        }

    }
};



async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const model = genAI.getGenerativeModel({ 
        model: "gemini-2.5-flash",
        
    });
    const fullSchema = zodToJsonSchema(resumePdfSchema, { $schema: false });
    const cleanSchema = {
        type: fullSchema.type,
        properties: fullSchema.properties,
        required: fullSchema.required
    };


    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    
    try {
        const result = await model.generateContent({
            contents: [{ role: "user", parts: [{ text: prompt }] }],
            generationConfig: {
                responseMimeType: "application/json",
                responseSchema: cleanSchema, 
                maxOutputTokens: 8192, 
            }
        });

        const response = await result.response;
        const text = response.text(); 
        const jsonContent = JSON.parse(text);

        return await generatePdfFromHtml(jsonContent.html);
    } catch (error) {
        console.error("Gemini Error:", error);
        throw error;
    }

}

module.exports = { generateInterviewReport, generateResumePdf }

    
        

